// <auto-generated />
namespace Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class OrderDetail1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderDetail1));
        
        string IMigrationMetadata.Id
        {
            get { return "202107012135498_OrderDetail1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
